// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Model;
using System;

namespace Database.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20171115225113_create")]
    partial class create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("Model.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("description");

                    b.Property<string>("name");

                    b.Property<float>("price");

                    b.Property<string>("type");

                    b.HasKey("id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("Model.Specification", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.Property<int>("productid");

                    b.Property<string>("value");

                    b.HasKey("id");

                    b.HasIndex("productid");

                    b.ToTable("specifications");
                });

            modelBuilder.Entity("Model.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("address");

                    b.Property<bool>("admin");

                    b.Property<string>("email");

                    b.Property<string>("gender");

                    b.Property<string>("name");

                    b.Property<string>("password");

                    b.Property<string>("phonenumber");

                    b.Property<string>("salt");

                    b.Property<string>("surname");

                    b.Property<string>("username");

                    b.Property<bool>("verified");

                    b.Property<string>("zipcode");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Model.Specification", b =>
                {
                    b.HasOne("Model.Product", "product")
                        .WithMany("specifications")
                        .HasForeignKey("productid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
